version: '3'

services:
  tecsallesdb:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: dW1jdGVjX2Rldl9kYg==
      MYSQL_DATABASE: tec_salles_dev_db
    ports:
      - "3306:3306"
    volumes:
      - C:\\Users\\weverton.souza\\Documents\\enviroment_two\\data-base\\docker\\tecsale:/var/lib/mysql
    networks:
      - tec-salles-network


networks:
  tec-salles-network:
    driver: bridge
